apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apache
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apache-web
  template:
    metadata:
      labels:
        app: apache-web
    spec:
      containers:
        - name: webserver
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80