apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://grafana.github.io/helm-charts' 
    chart: grafana
    targetRevision: 8.5.x
    helm:
      parameters:
        - name: service.type
          value: LoadBalancer
          annotations:
            service.beta.kubernetes.io/azure-load-balancer-internal: "true"
      values: |
        assertNoLeakedSecrets: false
        env:
          GF_SMTP_USER:
            valueFrom:
              secretKeyRef:
                name: grafana-smtp-secret
                key: user
          GF_SMTP_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: grafana-smtp-secret
                key: password
          GF_SMTP_FROM_ADDRESS:
            valueFrom:
              secretKeyRef:
                name: grafana-smtp-secret
                key: user
        grafana.ini:
          smtp:
            enabled: true
            host: smtp.gmail.com:587
            skip_verify: true
            from_name: Grafana Alerts
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

