name: Push Helm Chart to ACR
on:
  push:
    branches:
        - helm-charts

env:
  containerRegistryName: 'capstonemtnacr'
  containerRegistry: 'capstonemtnacr.azurecr.io'
  

jobs:
  build-and-push-helm-chart:
    name: Build and Push Helm Chart
    runs-on: self-hosted
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Helm Repo Login
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | helm registry login ${{ env.containerRegistry }} --username ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Loop through Helm Charts, Package and Push
      run: |
        echo "Starting automatic chart discovery..."
        
        find . -name "Chart.yaml" -exec dirname {} \; | while read -r chart_dir; do
          echo "--------------------------------------------------"
          echo "Found chart directory: $chart_dir"
          
          CHART_NAME=$(grep '^name:' "$chart_dir/Chart.yaml" | awk '{print $2}')
          CHART_VERSION=$(grep '^version:' "$chart_dir/Chart.yaml" | awk '{print $2}')
          
          echo "Packaging $CHART_NAME (Version: $CHART_VERSION)..."
          helm package "$chart_dir" --destination .
          PACKAGE_FILE=$(ls *.tgz)
          
          echo "Checking if version $CHART_VERSION already exists in ACR..."
          
          if helm show chart oci://${{ env.containerRegistry }}/charts/$CHART_NAME --version $CHART_VERSION; then
            echo "Version $CHART_VERSION of $CHART_NAME already exists in ACR. Skipping push."
          else
            echo "Version $CHART_VERSION is new! Pushing to Azure Container Registry..."
            helm push "$PACKAGE_FILE" oci://${{ env.containerRegistry }}/charts
          fi
          rm *.tgz
        done

